builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Your app's vendor.
    # Default is empty.
    vendor: KAYAK Software Corporation
    homepage: https://www.kayak.com
    maintainer: Neil Hanlon <nhanlon@kayak.com>
    description: A persistent SNMP script that exports TC Queue and Class statistics for graphing
    license: Apache 2.0

    formats:
      - rpm
      - deb
    dependencies:
      - iproute

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    config_files:
      "tc_reader.conf": "/etc/tc_reader.conf"
